branch-defaults:
  feature-aws_deployment:
    environment: env1
    group_suffix: null
global:
  application_name: website_reivew_tool
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
