name: CI

on:
  push:
    branches:
      - feature-unit_testing
      - main

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.9"
          - "3.10"
          - "3.12"
          - "3.12-dev"
          - "pypy-3.8"
          - "pypy-3.9"
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip version
        run: python -m pip install --upgrade pip

      - name: Update pip wheel
        run: pip install --upgrade setuptools wheel

      - name: Install MySQL/MariaDB dependencies
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y libmysqlclient-dev
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            brew install mysql-client pkg-config
            export PKG_CONFIG_PATH="/opt/homebrew/opt/mysql-client/lib/pkgconfig"
            pip install mysqlclient
          fi

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Drop and recreate test database
        run: |
          mysql -u root -e "DROP DATABASE IF EXISTS test_ebdb; CREATE DATABASE test_ebdb;"

      - name: Run tests
        run: python manage.py test login